### ISSUE TITLE
Super useful taskboard hard to find.

### ISSUE THREAD

**Issue by stephaniehobson** [taigaio/taiga-front#1013]
My team uses the task board the most but I always have trouble remembering where it is. It doesn't make sense to me to look in the backlog section for my current tasks. We use it enough to justify making it a top level menu item but I'm not sure if we're weird or representative.

**Comment by Xaviju** [comment]
We have an open enhancement to add a link to your current sprint in the main bar. 
https://tree.taiga.io/project/taiga/issue/1813

It raises some questions on possible edge cases that we still have to discuss. Please upvote it to raise awareness. If you add a comment here I will add it to the mentioned enhancement.

Closing this because is duplicated.
