### ISSUE TITLE
Watchers value unmodified after member removal

### ISSUE THREAD

**Issue by ersin-ertan** [taigaio/taiga-front#1052]
A private project which adds members turns those members into watchers.

However, assuming those members leave your organization and are removed from the project via the members tab, the number of watchers still reflects what it was prior to the removal.

I am uncertain as to whether or not notifications are sent to those individuals, testing yields 'no' at the moment.

**Comment by superalex** [comment]
Hello @ersin-ertan 

If the project is private those notifications won't be sent, the code checks if the user has at least view permissions for the item before sending that notification.

**Comment by ersin-ertan** [comment]
Thanks that's good to know. Also note 

> the number of watchers still reflects what it was prior to the removal.

which would be a visual bug as the number of watchers is showing an incorrect value.

**Comment by superalex** [comment]
Not really, in Taiga you can watch a project even if you are not a member of it. For example:
 - A user finds B project (public) and watchs it
 - A user receives notifications about changes in B
 - B project goes private
 - A user is still a watcher but doesn't receive any notifications
 - B project goes public again
 - A user receives notifications again

When we implemented this part we intentionally decided not to remove the "Notification Policy" for the user in the project because we couldn't distinguish if the user was a watcher before joining the project or not. Anyway we will review this decision with our UX people.

Thank you very much for reporting ;)

Regards,
