### ISSUE TITLE
Task complexity and scores

### ISSUE THREAD

**Issue by pinkra** [taigaio/taiga-front#1071]
As development team we want to add complexity in tasks so we can assign tasks to members by their complexity and track it later. It would be even great if scores in members area could take count of the task complexity (for example if i develop a task with high complexity my score is increased adequately).

**Comment by abdallahYashir** [comment]
+1
In our case, our user stories are broken into a lot of tasks and sometimes some of them are relatively complex while others are not. If we can assign them, the team lead know whom to assign the task to, depending on the skills of the members of the team.

Plus like @pinkra mentioned, keeping track of members' score makes it more interesting to work  because we usually organise healthy competitions with members who scored most points for a period in time for example. These kinds of challenges bring a different level of motivation :)
