### ISSUE TITLE
impossible to delete "blocked" project

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#1085]
I created test projects a long time ago, and now I see they are put as "blocked" , so I can't delete them. Which I think should be possible (as the alternative would to be pay and then delete them ...)

**Comment by bameda** [comment]
You can write to support@taiga.io and we will unblocked your projects so you can delete, transfer, export o make them public.

**Comment by allan-simon** [comment]
thanks for that, however can it be added somewhere , i mean an short text if not a dedicated feature? because if someone arrives tomorrow with the same issue, he will be as clueless as me :)

**Comment by bameda** [comment]
But there is already a big green button that sents you to the support page https://tree.taiga.io/support/subscription-and-plans/payment-process-faqs/#q.-why-is-my-project-blocked?

![download](https://cloud.githubusercontent.com/assets/877218/17408420/6aec4bf0-5a6b-11e6-8454-4821d321de73.png)

**Comment by allan-simon** [comment]
hmm very strange I don't get the same screen as you 
![selection_081](https://cloud.githubusercontent.com/assets/213167/17417827/f2341e2e-5ac7-11e6-9c72-8185ad1c7368.png)

**Comment by bameda** [comment]
Because you are the owner, but in the plans page there is a link to support pages too.

**Comment by allan-simon** [comment]
exact, but who will think about clicking on the plans page (that i expect only to show me button to pay to reactivate my project) when you only want to delete the project?

**Comment by bameda** [comment]
We unblocked your project because you stay in Taiga since the beginning so you are in the "special case". Normally if a project is blocked users will have to select a subscribed plan so the current behaviour is the correct one. We send a lot of emails (three or four, e. x. [[1]](http://us9.campaign-archive1.com/?u=d0381bdbd4e837df219d9c96a&id=ae5b56c0f6&e=ecb412ccbd), [[2]](http://us9.campaign-archive1.com/?u=d0381bdbd4e837df219d9c96a&id=f3ca3efd78&e=ecb412ccbd), [[3]](http://us9.campaign-archive1.com/?u=d0381bdbd4e837df219d9c96a&id=1c7682b230&e=ecb412ccbd)) to our users and project owners, show alert messages in the platform and publish some tweeets and post in or [blog](https://blog.taiga.io/taiga-pulsatilla-patens-release-20.html) in April to explain all the process.

**Comment by allan-simon** [comment]
hmmm ok I understand better now, thanks for the time you've taken to explain me.

**Comment by bameda** [comment]
You are welcome. Thanks to you for your feedback
