### ISSUE TITLE
loginFormType not passed in invitation

### ISSUE THREAD

**Issue by mroe1234** [taigaio/taiga-front#1192]
I'm looking at taiga-front/app/coffee/modules/auth.coffee:

The 'Login Directive'
passes the loginformType as seen below:

<code>promise = $auth.login(data, loginFormType) </code>

However the Invitation section does not:

<code>promise = $auth.acceptInvitiationWithExistingUser($scope.dataLogin)</code>

In order to properly handle plugable authentication the front end has to be aware of the loginformType.  

The github auth plugin seems to work because it actually creates its own button.

**Comment by mroe1234** [comment]
Can someone confirm this as a bug?

**Comment by superalex** [comment]
Hello @mroe1234 

Sorry, we confirm it's a bug, we fixed some weeks ago in the stable branch and will be included in the next release.

Regards,

**Comment by pstreef** [comment]
@superalex 

Concerning this bug (in combination with using case sensitive email addresses)

Conciser a user with email bla@bla.nl and a case insensitive email server.
I add him to a project, he gets the invitation and registers. All is well in the world... However, when I create a new project and send the invite to BLA@bla.nl he would receive another invite! Ok there seems to be good reasons for this (some servers handle uppercase prefixes differently and all, see https://tree.taiga.io/project/taiga/issue/2586) but if the user clicks on the invite and logs in using the plugin login form he gets a message "you are added to project bla2" but he is not added at all and sent to permission denied view.

I'm not sure if this is because of this bug, or if it is a totally different problem..
