### ISSUE TITLE
Code formatting in wiki is ultra ugly

### ISSUE THREAD

**Issue by tiffon** [taigaio/taiga-front#1213]
**Do you want to request a *feature* or report a *bug*?**

More like suggest an improvement.

**What is the current behavior?**

In the wiki, when inline `code` is rendered it is presented in a way that is inconsistent with the rest of the UI, as shown in the screenshot, below, with a dark background. 

<img width="958" alt="screen shot 2017-01-20 at 10 48 49 pm" src="https://cloud.githubusercontent.com/assets/2304337/22171731/a7091b78-df62-11e6-81b9-f49e8c324792.png">

Additionally, code blocks have a dark background, as well, as shown in the screenshot. Also, for javascript (not sure about other languages), the syntax highlighting is kind of awful with comments being virtually invisible.

**If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**What is the expected behavior?**

Something more visually integrated with the rest of the UI.

**Is it happening in taiga.io or in your own instance?**

taiga.io

**What browser/version are you using?**

```
Google Chrome	57.0.2987.0 (Official Build) canary (64-bit)
Revision	ad51088c0e8776e8dcd963dbe752c4035ba6dab6-refs/heads/master@{#444943}
OS	Mac OS X 
JavaScript	V8 5.7.492
```

**Are there any console errors *(Ctrl + F12)* in red?**

Here is the console output from the page-load:

```
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
angular.js:13550 Initialize navigation urls
angular.js:13550 Initialize api urls
angular.js:13550 Using the RavenJS exception handler.
angular.js:13550 Initialize resources
angular.js:13550 Initialize application
angular.js:13550 HeartBeat enabled
angular.js:13550 WebSocket connection opened
angular.js:13550 Subscribe to: notifications
angular.js:13550 HeartBeat send PING
angular.js:13550 WebSocket message received: {"cmd":"pong"}
angular.js:13550 HeartBeat recived PONG
```

**Comment by Xaviju** [comment]
Hi, @tiffon 

**What is the expected behavior?**
Something more visually integrated with the rest of the UI.

We understand that the aesthetics of the code formatting in Taiga do not appeal to you. Any specific suggestion on how to improve it? 

It will be nice to hear other opinion as well.

**Comment by tiffon** [comment]
Hi @Xaviju,

Re specific suggestions, GitHub has a nice aesthetic. For instance, the `inline code` look nice, as do

```
code blocks
```

Emulating GH might not be an attractive long-term goal, but it's a starting point.

Great work on Taiga!

**Comment by Ratismal** [comment]
I also agree with this. Comments on the wiki are unreadable due to them being nearly the same colour as the background. Additionally, on javascript template literals do not display correctly.
![image](https://cloud.githubusercontent.com/assets/1059362/23080848/9d5ed870-f50f-11e6-97b5-ba3050355759.png)
Inline codeblocks also do not align properly with the rest of the text. 

> Any specific suggestion on how to improve it?
I personally think you should lighten up the background of codeblocks. Make it consistent with the rest of the page; perhaps slightly darker than the existing background. The current colour is a (subjectively) puke-grey, and is not found anywhere else on the site. Please revise.

Perhaps implement the ability to change code themes. ex. monokai, solarized, tomorrow night, etc. At the very least, take inspiration from the colour contrast of existing themes. A quick google search provided [this](http://color-themes.com/?view=index) as a good reference.

I love Taiga, but I honestly can't stand the current state of the wiki.

**Comment by Xaviju** [comment]
Thanks for the link @Ratismal. Very useful!

**Comment by edmundhighcock** [comment]
I love Taiga but definitely agree with these comments! Is there any progress here?

**Comment by foliovision** [comment]
If simple (simple is usually good), at least **following the conventions of GitHub would be very welcome**.

It would also be nice to choose which language syntaxing works by default (sometimes auto-parsing can get it wrong on smaller samples) on a block.

**Comment by edmundhighcock** [comment]
Any thoughts here? This a big flaw in an otherwise great app. Even just having the option of having 'Courier New' with no syntax highlighting would be preferable to the current formatting.
