### ISSUE TITLE
Oh my ducking god

### ISSUE THREAD

**Issue by artificialidentity** [taigaio/taiga-front#1358]
Please add an unescapable confirmation message when you hit escape button in edit mode. I can not count the number of time I have accidentally hit the escape button when reaching for the ` key to enter code blocks.

It really sucks to lose something you have been writing for the last 40 minutes.

**Comment by theriverman** [comment]
+1

**Comment by yukoff** [comment]
Better just exit edit mode by <Esc><Esc> (double-<Esc>). So when smb hit <Esc> accidentially - it should be sound notification (well, I'm not quite sure how to describe it... maybe gentle "boom" sound? ;) and a closable baloon/tooltip saying "Hit escape twice to exit edit mode", no need for confirmation (it becomes really inconvenient when doing a lot of edits).

**Comment by jespino** [comment]
I'm working on it.

**Comment by i-need-to-tell-you-something** [comment]
> no need for confirmation (it becomes really inconvenient when doing a lot of edits).

As long as the confirmation can be confirmed by keyboard (e.g. <kbd>Enter</kbd>), then it won't be so inconvenient. E.g. <kbd>Esc</kbd> + <kbd>Enter</kbd>. It will become a quick motion in no time.

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. Thank you very much on behalf of the Taiga Team!
