### ISSUE TITLE
Wrong home-icon-url for guest users

### ISSUE THREAD

**Issue by graabein** [taigaio/taiga-front#1382]
Using selfhosted version (cloudron.io)

The Taiga main home-icon-url for guests (not logged in users) point to taiga.io instead of to the local cloudron Taiga-installation. This problem is not present for logged in users, for whom the home-icon-url correctly point to the root of the local cloudron Taiga installation.

![taiga-home-icon-url](https://user-images.githubusercontent.com/9559189/32135883-716b0a9a-bc06-11e7-897c-146e4e7dbf06.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Fire up a selfhosted install, then as GUEST (not logged in user) click on the upper left starlike home-icon (you then end up at http://taiga.io)

**What is the expected behavior?**
Guest users clicking the upper left home-icon should be sent to the root directory of the local installation instead of to taiga.io

**Is it happening in taiga.io or in your own instance?**
Using selfhosted version (cloudron.io)

**What browser/version are you using?**
All versions, this is a Taiga issue, not browser related

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by graabein** [comment]
Could probably be fixed here: https://github.com/taigaio/taiga-front/blob/master/app/modules/navigation-bar/navigation-bar.jade#L5

**Comment by jespino** [comment]
Hi @graabein, this is not an accidental bug, is an intentional feature.

Anyway, if anybody wants, we'll accept a PR changing it for a "configurable" link. For example, add in the conf.json, "anonymousHomeUrl", with null value by default, and if this is defined, use it when is anonymous, if not, use the "home" url always.

**Comment by graabein** [comment]
Hi @jespino and thanks for answering.

I think this intentional feature is very confusing for the anonymous users.  If they browse a project, they have no way to find their way back to the root of the installation in order to see other projects. Why is this feature intentional?

An important purpose, at least for some Taiga owners with local installations, is to attract new users/contributors where some of these users may be totally new and unfamiliar, both to Taiga and to kanban.  They may be interested, browse around to see what is going on in this local Taiga installation, and suddenly they find themselves totally frustrated on http://taiga.io instead of staying on the website/project they intentionally visited in the first place.  Maybe they see this is a mess, and they just leave and never come back.  Maybe this was exactly the visitor you needed to join your project, instead he/she is sent away to some totally unrelated community.

I hope you will change this to a configurable link.

**Comment by jespino** [comment]
I completely understand your point of view and I agree, have this as a configurable field, is probably the best approach.

**Comment by Amolith** [comment]
It's been over a year and they still haven't merged the pull request above even though it's a click away. I patched it by finding the file the string was in (`~/taiga-front-dist/dist/v-1555485225914/js/templates.js`) and replacing it with my instance URL. The dir will change with each version so it may be different for you. You can use the commands below if you installed Taiga on Linux.

**Find the file:**
`find . -type f -exec grep -H 'https://taiga.io' "{}" \;`

**Find all occurrences of taiga.io and replace them** 
*(make sure you replace \<instance-url\> with yours*
`find . -type f -exec sed -i 's|https://taiga.io|<instance-url>|g' "{}" \;`

It would be better take the longer route (first command) and manually replace the occurrences because doing them all recursively as in the second command may break things.

**Comment by beatstream69** [comment]
For docker-compose comment out line `image: taigaio/taiga-front:latest` insert below `build: ./build/front`
and create file `./build/front/Dockerfile`:
`FROM taigaio/taiga-front:latest`
`RUN find /usr/share/nginx/html -name "templates.js" -type f -exec sed -i 's|https://taiga.io|<instance-url>|g' "{}" \;`
