### ISSUE TITLE
project members not properly displayed

### ISSUE THREAD

**Issue by updiversity** [taigaio/taiga-front#1385]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
As you can see the administrator user looks to not being displayed properly. It happens with all the users, and on several browsers (Firefox, Chrome, Chromium). And it is happening everywhere.

![image](https://user-images.githubusercontent.com/7083365/32655663-d8365830-c60e-11e7-99a2-614ec22e198a.png)
![image](https://user-images.githubusercontent.com/7083365/32655719-23f3a386-c60f-11e7-87c6-1891f9fef770.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Clean UI

**Is it happening in taiga.io or in your own instance?**

Own instance, fresh vagrant deploy

**What browser/version are you using?**

Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**

No

Thanks for reporting!

**Comment by theriverman** [comment]
I experience the same issue in my own, pure instance (no vagrant/docker/etc...).
However, If I manually change the avatar of the user, the problem is gone. 
By default, the frontend tries to load the default user images from an invalid url.

By invalid url, I mean the real url (painted black on my screenshot) gets concatenated with `io.wp.com/`
For example, if your Taiga instance's url is `taiga.company.com`, then the frontend will try to load the avatar from `http://io.wp.com/taiga.company.com/avatar.png`
![weird_url](https://user-images.githubusercontent.com/22156894/32657203-21cd68fc-c615-11e7-84fa-f3bc4f3f1b5e.png)

**Comment by updiversity** [comment]
Thanks, it works !
