### ISSUE TITLE
Users cannot register - invisible checkbox

### ISSUE THREAD

**Issue by 23ryqi3fihq** [taigaio/taiga-front#1462]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Users can't create a new account

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to taigahost/register

```
<tg-terms-of-service-and-privacy-policy-notice target="data.accepted_terms">
<!----></tg-terms-of-service-and-privacy-policy-notice>
```

Is invisible and prevents user from checking it, therefore user can't register.

**What is the expected behavior?**

Element 
```
<tg-terms-of-service-and-privacy-policy-notice target="data.accepted_terms">
<!----></tg-terms-of-service-and-privacy-policy-notice>
```

should be visible.

**Is it happening in taiga.io or in your own instance?**

My own instance, I followed step-by-step production installation tutorial.

**What browser/version are you using?**

Firefox and Chromium

**Are there any console errors *(Ctrl + F12)* in red?**

No.

**Comment by dangarbar** [comment]
The directive tg-terms-of-service-and-privacy-policy-notice displays a text with the Privacy Policy and Terms of Service that must to be accepted (by marking a checkbox field), so that the SIGN UP button will become enabled.

This checkbox field needs that the privacyPolicyUrl and the termsOfServiceUrl have been defined in your conf/conf.json file to be shown. However, in private instances like yours you mustn't need to define this variables to allow users to register, so we just already fixed this issue in the pull request #1463
