### ISSUE TITLE
Cloud - can't delete old projects nor create new ones

### ISSUE THREAD

**Issue by fredericocarneiro** [taigaio/taiga-front#1561]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I see my projects but I cant really manage them. I cant delete nor edit. When I click on it, I get a screen asking me to subscribe but I'd like to get the 1 free private project that Taiga Offer. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1 - After login, I click on "Projects" link.
2 - My two old projects are listed but there isnt any link to project admin page. I can only click on them and when I do that, I get the message : "BLOCKED PROJECT - Don't worry, it should be temporary.
To unblock projects, first subscribe to a payment plan that allows at least as many private projects as you have currently"

**What is the expected behavior?**
I'd like to access the project admin page and delete these two projects in order to create a new project to fit in the free layer.

**Is it happening in taiga.io or in your own instance?**
Taiga Cloud

**What browser/version are you using?**
Chrome v68 

**Are there any console errors *(Ctrl + F12)* in red?**
I belive its a server error.

Thanks for reporting!

**Comment by divoxx** [comment]
This is also an issue to me. I've tried Taiga a long time ago and created two projects as a trial.

Now, after some years, I was going to research Taiga again to see if it fits our currently need but I'm currently blocked because the 2 projects are blocked and there is no way to delete them.

I understand there is a 1 private project limit, which is more than enough for my testing, but I can take advantage of the free tier if all my projects are blocked and I can't delete them to free up the space.
