### ISSUE TITLE
Filter negation

### ISSUE THREAD

**Issue by benyanke** [taigaio/taiga-front#1722]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, if you want to select all the US statuses except one, you have to select all of them in the filter.

**What is the expected behavior?**
It would be useful to be able to use negation of a filter, instead of manually doing this.

**Comment by alexhermida** [comment]
@benyanke since version [4.1.0](https://github.com/taigaio/taiga-front/blob/master/CHANGELOG.md#410-2019-02-04) Taiga has negative filters feature. We updated changelog still we didn't publish at blog.taiga.io last minor releases changes.

![negative_filters](https://user-images.githubusercontent.com/4062867/54124988-1b4b7a00-4404-11e9-998b-c50cbf022356.png). I hope this help you.

Thank you!
