### ISSUE TITLE
Adding a newline after a header disables text input

### ISSUE THREAD

**Issue by jwir3** [taigaio/taiga-front#1878]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Typing enter after editing a heading does not allow for typing.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Edit a wiki page.
2. Add a heading by typing some text, highlighting it, and then selecting H1 or H2 in the context menu.
3. Add a word to the end of the heading.
4. Type enter/return.

**What is the expected behavior?**
A new line should be added, with the cursor on the new line, ready to type text in paragraph format. Instead of this, a new line is added, and the cursor is on this new line, but typing results in no characters shown. Instead, one must click in the edit box again to enable typing.

**Is it happening in taiga.io or in your own instance?**
**What browser/version are you using?**
Our instance. Currently running version `2.1.0` of taiga-front. Using Firefox 73.0.1 on Mac.

**Are there any console errors *(Ctrl + F12)* in red?**
No.

Thanks for reporting!

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. 
Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
