### ISSUE TITLE
Undo after adding a code block does not undo the code block

### ISSUE THREAD

**Issue by jwir3** [taigaio/taiga-front#1879]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
After adding a code block using the context menu, and then typing CMD+Z, the addition of the code block is not undone.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open a new wiki page
2. Add some text.
3. In the middle of the text, select a word and surround it with backticks to indicate an inline code block.
4. Remove the backticks surrounding the word.
5. Highlight the word, and from the context menu, select code block.
6. Type CMD+Z to undo the addition of a code block.

**What is the expected behavior?**
The code block should be undone and the word restored, without backticks, first. Subsequent undo operations should restore the backticks.

**Is it happening in taiga.io or in your own instance?**
Our own instance.

**What browser/version are you using?**
Version 2.1.0 of taiga-front, with some modifications added to include https://github.com/taigaio/taiga-front/pull/1762 and https://github.com/taigaio/taiga-front/pull/1758

**Are there any console errors *(Ctrl + F12)* in red?**
No.

Thanks for reporting!

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
