### ISSUE TITLE
Tag filtering - 'and' instead of 'or'

### ISSUE THREAD

**Issue by nicoppola** [taigaio/taiga-front#1880]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When filtering the backlog on more than one tag, the backlog is filtered by or-ing the two instead of and-ing.

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
I would like to be able to filter the backlog by user stories that contain a set of tags and epics, excluding all others.

**Is it happening in taiga.io or in your own instance?**
My own instance

**What browser/version are you using?**
Chromium Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by blaggacao** [comment]
Incredible, that's unusable.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. 
Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
