### ISSUE TITLE
Can't intra-link wiki pages with non-latin titles using editor UI

### ISSUE THREAD

**Issue by landergate** [taigaio/taiga-front#1886]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Articles with a non-latin name created through "Add bookmark" couldn't be intra-linked using editor visual interface, as it wouldn't rename linked URL using latin-only characters.

Clicking on a such intra-wiki link results in opening a totally different blank unexisted page, because it doesn't honor latin-only URL conversion.

Inconsistent behavior results in intra-links being unusable for common users.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a wiki article with a name "Тест" using "Add bookmark" button.
2. Page created with a translated latin-only URL: "/test"
3. Link a "Тест" page on any other page.
4. Click on that link.
5. Different blank page with non-latin URL is being opened.

**What is the expected behavior?**
Using intra-link results in opening linked page.

So visual editor must honor URL latin-only conversion on creating an intra-link (e.g. only if link typed using short URL, which implies intra-link), or backend to prevent conversion non-latin page titles to a latin-only URL.

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Firefox 74.0

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
