### ISSUE TITLE
Feature request - Support for custom jitsi server URL

### ISSUE THREAD

**Issue by zeigerpuppy** [taigaio/taiga-front#1892]
It would be great if the jitsi server URL was configurable.
This would allow use of self-hosted/alternative jitsi servers.

As far as I can see, there's only one control that would need updating to an optional field:

https://github.com/taigaio/taiga-front/blob/d79dc7a010caabec957363d17cb74d743bd257b8/app/modules/components/project-menu/project-menu.controller.coffee#L108

**Comment by zeigerpuppy** [comment]
I tested changing the URL in the compiled `js/app.js` file and it works, so if anyone wants to manually change the URL to a jitsi server, it can be accomplished using that method for the moment.

**Comment by dheche** [comment]
You can select "Custom" video conference system in Meet Up Module and fill your self hosted/alternate jisti room url there.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
