### ISSUE TITLE
UI-Bug: A search query is filtering the Kanban Board and not visible in the UI.

### ISSUE THREAD

**Issue by rscircus** [taigaio/taiga-front#1902]
**What is the problem here?**

The problem is best described with an image. Imagine you come back to work and suddenly see an empty Kanban Board.

![image](https://user-images.githubusercontent.com/1167114/81146018-c8257680-8f77-11ea-9036-19bffa1ef1c7.png)

**What is the current behavior?**

After close inspection one can see in the location bar, that a search query is active. However, that is not visible in the UI. Hence, the user gets confused.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://taiga.blah.de/project/sthsthsth/kanban?q=invisibleproblem

**What is the expected behavior?**

UI shows that a search is active and filtering the Kanban board.

**What browser/version are you using?**

Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**

No.

**Comment by rscircus** [comment]
Moderator's, I'm happy to fix it if it wasn't fixed in another way already. :-)

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
