### ISSUE TITLE
GitHub import screen is not properly readable

### ISSUE THREAD

**Issue by madmath03** [taigaio/taiga-front#1911]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The GitHub import screen is not properly readable: 
1. text white on light background
2. not enough space for text under buttons

![image](https://user-images.githubusercontent.com/6967675/81751896-a9ac0780-94b0-11ea-9be6-1ca267419f90.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Simply import a GitHub project into Taiga.

**What is the expected behavior?**

Screen readable.

**Is it happening in taiga.io or in your own instance?**

Both.

**What browser/version are you using?**

Anyone

**Are there any console errors *(Ctrl + F12)* in red?**

None. Simply CSS issue.
Going to provide PR for this.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
