### ISSUE TITLE
duplicated bulk-add tasks

### ISSUE THREAD

**Issue by jdpipe** [taigaio/taiga-front#1914]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
While setting up a new project, I used bulk-add to populate my list of tasks in Kanban. Somehow the system added most of my tasks twice, which was then a huge pain to delete.

**If the current behavior is a bug, please provide the steps to reproduce.**
I don't know. The website is not very responsive, so perhaps I clicked the 'submit' button more than once.

**What is the expected behavior?**
Bulk-add tasks should have a unique description. It should be impossible to add a new task with a description equal to an already-existing non-closed task.

**Is it happening in taiga.io or in your own instance?**
This was on taiga.io

**What browser/version are you using?**\
Firefox on Ubuntu

**Are there any console errors *(Ctrl + F12)* in red?**
Doesn't matter -- this has at least propagated through to the backend, so it's at least also a backend problem.

Thanks for the nice software, guys!

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
