### ISSUE TITLE
tasks without assign

### ISSUE THREAD

**Issue by jdpipe** [taigaio/taiga-front#1915]
**Do you want to request a *feature* or report a *bug*?**
FEATURE REQUEST

**What is the current behavior?**
This feature request relates to single-user Kanban -- ie 'to do list' usage. In that use-case, it is not very useful to show the  'Not assigned' button everywhere. Even if I was to assign these tasks all to myself, it would still be using up a lot of screen space. Instead, it is suggested for a much smaller "+assign" button to appear when mousing over tasks, but no text should be shown there by default.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply create a list of tasks without assigning a user. Every task has the following header:

![image](https://user-images.githubusercontent.com/87423/82748655-2e6b1f80-9de7-11ea-8352-7d27442c0b75.png)

**What is the expected behavior?**
I would rather not see that 'Unassigned' label, at least for projects that only have one participant.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Firefox 76.0.1 on Linux

**Are there any console errors *(Ctrl + F12)* in red?**
NA

Thanks for the great software!

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through.

Thank you very much on behalf of the Taiga Team!
