### ISSUE TITLE
I can't unassign a user from the Taskboard view when I edit a task

### ISSUE THREAD

**Issue by bameda** [taigaio/taiga-front#1921]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I can't unassign a user from the Taskboard view when I edit a task. After unassigning it in the edit modal, when saving the changes, the task remains assigned and no request is sent to the backend

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to a taskboard with assigned tasks
2. Open edit modal from an assigned task.
3. Unassign the task
4. Press Save 

**What is the expected behavior?**

The task should be unassigned

**Is it happening in taiga.io or in your own instance?**

In taiga.io

**What browser/version are you using?**

Firefox and Chrome, last version

**Are there any console errors *(Ctrl + F12)* in red?**

Nope.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
