### ISSUE TITLE
Editing tasks from subtask view doesn't apply changes or loads indefinitely

### ISSUE THREAD

**Issue by ganmatthew** [taigaio/taiga-front#1935]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
Whenever I try to edit a task's data (e.g. name, status, assigned person) from the subtask view, it usually gets stuck loading for a long time, or the dropdown menu option changes but doesn't save.

The blue circle is the color of the dropdown menu option that is saved, while the red circle shows that the dropdown menu option is not being saved.

![image](https://user-images.githubusercontent.com/24535419/89709294-287de700-d9b1-11ea-8377-a2fa856e944d.png)

However, if I change the task's data from the task page itself, it works fine with no problems.

I'm using Microsoft Edge Chromium (84.0.522.52) on Windows 10 version 2004 (build 19041.388). This error usually appears in console every time the issue happens:
![image](https://user-images.githubusercontent.com/24535419/89709234-b5747080-d9b0-11ea-9d63-8655e17ce74b.png)

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
