### ISSUE TITLE
FR: prominently show tags

### ISSUE THREAD

**Issue by blaggacao** [taigaio/taiga-front#1941]
![image](https://user-images.githubusercontent.com/7548295/91197977-9882b180-e6c1-11ea-81ef-bf96db320119.png)

There is an arguable advantage of using tags more prominently on larger projects.

I'll say this: It's at the very least a lot more useful than this metadata
![image](https://user-images.githubusercontent.com/7548295/91198115-c7008c80-e6c1-11ea-8496-b6cb28cd74c0.png)

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
