### ISSUE TITLE
FR: ghf markdown (with task lists)

### ISSUE THREAD

**Issue by blaggacao** [taigaio/taiga-front#1942]
![image](https://user-images.githubusercontent.com/7548295/91198344-0e871880-e6c2-11ea-92d6-4d6bfbd8a8c1.png)
should be renderd as task list

- [x] tasklist
- [ ] tasklist

and put in the card's metadata, like so:
![image](https://user-images.githubusercontent.com/7548295/91198404-2068bb80-e6c2-11ea-8956-39ff87cef7ad.png)

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. Thank you very much on behalf of the Taiga Team!
