### ISSUE TITLE
FR: clipboard copy image upload

### ISSUE THREAD

**Issue by blaggacao** [taigaio/taiga-front#1943]
Pasting images from clipboard copy should behave like github, currently the output is a bit curious:
![image](https://user-images.githubusercontent.com/7548295/91199020-efd55180-e6c2-11ea-9f18-b0af30fd4cf5.png)

**Comment by cenggel** [comment]
need this feature too

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
