### ISSUE TITLE
FR: improve tag subsystem

### ISSUE THREAD

**Issue by blaggacao** [taigaio/taiga-front#1946]
See also #1880 #1187 #192 #1288 

- [ ] proper filtering
- [ ] tag colors (bug when creating inline) - not shown

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
