### ISSUE TITLE
When something is filled in the 'tag' textfield of a story, and the user leaves the view, assume they want to save that tag.

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#195]
Right now, you have to explicitly press 'Return' (or 'Tab'?) to save a tag to a story. However, this took me quite some time to figure out.

If someone types something in the tag field (and other fields) and leaves the view willingly, assume they want to save the changes, or display an alert mentioning there are unsaved changes. It would help in clarity.

**Comment by AdrianSchurz** [comment]
+1 Since explicit and concise descriptions for all types of tasks are encouraged (as should be the case), it is advised to eliminate possible sources of frustration/loss of work when trying to do exactly that. Changing the view is also not always intentional. I, for one, frequently derp out and hit a button on the side of my mouse or accidentally click link.
