### ISSUE TITLE
WYSIWYG (HTML) editor no appearing on self hosted v5.5

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-front#1965]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On taiga.io when in HTML mode and editing a comment or description and a word is highlighted a WYSIWYG editor pops up to allow formatting. For some reason this does not happen on a locally installed instance we use, but does work fine on taiga.io.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure if it is a bug or if some step of the update process was missed. I was expecting to see errors in the console on the local instance but there are none.

**What is the expected behavior?**
I expected to see the WYSIWYG editor bar popup up when I highlight some text but it does not (on local instance only)

**Is it happening in taiga.io or in your own instance?**
Own instance and not on taiga.io (just checked)

**What browser/version are you using?**
Firefox 81.01b

**Are there any console errors *(Ctrl + F12)* in red?**
There are no console errors

The frontend repo is currently on `origin/stable` which is equal to the `5.5.0-stable` tag.
The backend repo is currently on `origin/stable` which is equal to the `5.5.2` tag.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
