### ISSUE TITLE
Stretched layout on mobile browser

### ISSUE THREAD

**Issue by zeigerpuppy** [taigaio/taiga-front#238]
On iOS 5 (I know it's ancient but still works fine!) with Safari or Atomic Web browsers,
Taiga images look stretched vertically and it is not possible to access the login box.

**Comment by Xaviju** [comment]
Can you please tell us which safari version are you using?
We could have some issues in old safari versions because we are using quite new CSS features like flexbox and SVG images. Safari 6 doesn't always support this features without prefixes and fallback is not always provided (that could be a bug).

**Comment by Xaviju** [comment]
And please tell us if the problem is on taiga.io (landing page) or tree.taiga.on (app). On the last one, we don't have mobile support yet.
Thanks!

**Comment by zeigerpuppy** [comment]
The Safari version is the standard iOS Safari from iOS 5.0.1 (9A405).
The problem is on the landing page (taiga.io) and also on my instance which I have installed on my server.

**Comment by Xaviju** [comment]
Sorry @zeigerpuppy but mobile browsers are not supported. Old Safari versions both in mobile and desktop have some problems with standar svg. Your local app or tree.taiga.io may not work on mobile browsers.

It in our roadmap to develop a mobile version of taiga in the near future.
