### ISSUE TITLE
Make Kanban view responsive

### ISSUE THREAD

**Issue by andreas-becker** [taigaio/taiga-front#249]
Kanban view should be responsive, or at least get a optimized print-layout.

**Comment by Xaviju** [comment]
Hi @andreas-becker thanks for using Taiga.

At the moment *Taiga is not supporting mobile browsers* but its in our roadmap to create a mobile-friendly version. 
About the *optimized print layout*, I will add it as an idea to our enhancement list and will be reviewed by the team.

Thanks!

**Comment by Zorlin** [comment]
@Xaviju For what it's worth, Taiga mostly works great on my Nexus 5 running Android 5.

**Comment by jaywink** [comment]
Not really talking about just the board myself, but this was the only issue I found and didn't want to open a new similar one. The whole site except for front page does not follow responsive design principles, making it a huge pain to use on a mobile phone.

I've kinda tried to fall in love with Taiga. I almost did, until I logged in on the way home on the metro to update a task description for an upcoming new project I had filled some backlog for already. As the site itself is such an awesome job, I was kinda shocked and surprised that it rendered everything the same regardless of the width of my browser. Just logging in was hard work of pinching and zooming.

The solution is not to create a "broken" mobile version where you cannot do the things you want. See for example GitLab, who do a fantastic job of allowing you to do everything via a mobile browser, but rendering it using responsive principles. Those principles have been designed exactly to allow web sites to render *the same content* for different window sizes, but allowing it to be usable for all sizes.

I understand that the decision was made partly by looking at the numbers of mobile users using the site (reading in some Taiga issue I found on Taiga itself, but couldn't comment on it). However, how would anyone currently use the site with a mobile - the stats is automatically going to say "no one uses mobile" if the site itself *doesn't work on mobile*? :)

Taiga has huge promise, but not being able to quickly login from *anywhere* to update stuff is a huge blocker for me at least, so for this project going to move it to GitLab and check back at Taiga in the future.

Looking forward to a future (fully working, not broken like GitHub's mobile page where you can only do 50% of the things!) Taiga responsive view ;)

**Comment by Xaviju** [comment]
Hi @jaywink
I understand your point, but Taiga is not responsive for more reasons. One of the main principles of responsive websites is not related to the UI, but to the performance in mobile devices and their browsers under a (_probably_)  ~3G speed. Taiga makes a huge use of http requests and loads a lot of small chunks of modular data because we need to keep the site as fast and responsive as possible. We do not want to drain batteries or have bad mobile experiences. For the time being, we focus on doing something, but doing it well.
This could be faster and simpler if a different UX/UI would make a reduced consumption of data and a better experience for users, just in a different way, closer to a expected mobile device experience. We already made some wireframes and developed some ideas but we are still far from it. Making Taiga responsive (UI and performance) its something that takes some time, and we are a small team.
At the beginning of Taiga we decided to go with a desktop version as our first release and test it. Taiga has grown a lot in one year but we still on beta, fixing and improving basic features. We really want to deliver a fast, usable, elegant and beautiful mobile experience. I will be happy to check sites like gitlab for inspiration (Taiga <3 Gitlab btw) 

Thanks a lot for the feedback, we will be happy to see you again (and discuss) a future Taiga mobile version. 

PS. Making Taiga UI responsive would not be a huge deal, since our CSS is ready to be made responsive easily. We have a themes feature that can make the trick. https://taigaio.github.io/taiga-doc/dist/#themes
PS2. Some people of the community started developing a Taiga mobile version for android and iOS but we still have no news of this projects status.

**Comment by mikaoelitiana** [comment]
Hello all

I am also looking forward to this enhancement m. We are developing mobile app and we use taiga to manage our project development. Having a full support on mobile makes it easy for us to upload screenshots of bugs directly from smartphone to taiga.

**Comment by iGormilhit** [comment]
👍 For sure, a responsive UI would be a major enhancement!

**Comment by vahid07** [comment]
I hope see a responsive UI for Taiga project as soon as possible...
