### ISSUE TITLE
UX Issue on Backlog Page

### ISSUE THREAD

**Issue by emanuelvianna** [taigaio/taiga-front#259]
Hi fellows,

We experienced a problem here in the UX of the Backlog Page (I don't know
if this is the correct name). The Burndown is plotting a negative chart. The screenshot 
showing the bug is as follows:

![Screenshot](http://i.imgur.com/JC4qnU7.png)

Fell free to contact us case you need more information.

Very best regards,
Emanuel

**Comment by Xaviju** [comment]
We should update our support page to explain better what our graphs means:

- The **gray shadow** would be your "**recommended speed**". If your project's length is 100 points and 5 sprints it will 'recommend' you 20 points per sprint.
- The **green line** is your actual speed, **points per sprint**.
- **Dark red** is the increase of your backlog points because of **team requirements** (internal)
- **Light red** is the increase of your backlog points because of **client requirements** (external)

Hope it helps.
