### ISSUE TITLE
Apache2

### ISSUE THREAD

**Issue by ronlinet** [taigaio/taiga-front#364]
All tutorials are about ngnix installation. 
Is this tool supposed to run on apache2 platform? 
Has anybody tried ?

**Comment by jespino** [comment]
We (Taiga team) don't tried it, because we use nginx, but in this case isn't important to use nginx or apache, because the usage of nginx is only as reverse proxy to the real application server (gunicorn) in taiga-back. And in the case of the taiga-front this is a javascript application without special needs on web server, only serve the files.

Apache2 can server Taiga, but we haven't documentation about it. sorry.
