### ISSUE TITLE
Can only connect to Taiga-Front from host machine...

### ISSUE THREAD

**Issue by Eschin** [taigaio/taiga-front#367]
Following these docs http://taigaio.github.io/taiga-doc/dist/setup-production.html#_introduction, along with the setup-development docs, I have a taiga server setup and running, but I can only access the front-end from the host machine itself.

When I try connecting to taiga-front from a machine other than the host, I get the Oompa-Loompa error.  Looking in the JavaScript Console, I'm pretty certain this is my problem; OPTIONS http://localhost:8000/api/v1/projects net::ERR_CONNECTION_REFUSED

I've been digging through config files and altering settings all day, following along the other threads reporting similar issues, and all I can seem to do is break the front end on the host itself, but never accessing the taiga-front from any other machine.

I'm thinking, right now, the issue lies in the /etc/nginx/sites-available/taiga file... I've tried setting up the proxy_ settings, but nothing seems to work... maybe I've got the wrong settings...?

Any help would be appreciated :)

~Thanks

**Comment by superalex** [comment]
Hello @Eschin,

It sounds like your front app it's not currently configured, here http://taigaio.github.io/taiga-doc/dist/setup-production.html#_frontend_installation you have a conf.json example with the API url settings .

You should also check your host settings in ~/taiga-back/settings/local.py are overwriting correctly the attributes: MEDIA_URL, STATIC_URL, ADMIN_MEDIA_PREFIX and SITES you can find an example in the 6.2.1 point of the doc.

Regards,

**Comment by Eschin** [comment]
Still no luck... I can browse to the Taiga-Front login screen successfully from the host machine, but I get the Oompa Loompa error from any other machine on the network when I try to access the Taiga-Front page.

As you can see, I'm just trying to setup this server for access from within our LAN only, for the time being.  The site files are currently stored in the /home/ramos/ directory, and I've adjusted the nginx config to compensate for that.

Thanks again for the assistance :)
I kinda feel this is (hopefully) a simple setting I'm not catching.... Here are the current configurations;

**/home/ramos/taiga-back/settings/local.py**
```
    from .common import *

    MEDIA_URL = "http://10.1.10.151/media/"
    STATIC_URL = "http://10.1.10.151/static/"
    ADMIN_MEDIA_PREFIX = "http://10.1.10.151/static/admin/"
    SITES["front"]["scheme"] = "http"
    SITES["front"]["domain"] = "10.1.10.151"

    SECRET_KEY = "7ygyuibhcr6b78npmh89y9hujd5scdb6fi7nuybg67ty"

    DEBUG = True
    TEMPLATE_DEBUG = False
    PUBLIC_REGISTER_ENABLED = True

    DEFAULT_FROM_EMAIL = "no-reply@example.com"
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

    # Uncomment and populate with proper connection parameters
    # for enable email sending.
    #EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    #EMAIL_USE_TLS = False
    #EMAIL_HOST = "localhost"
    #EMAIL_HOST_USER = ""
    #EMAIL_HOST_PASSWORD = ""
    #EMAIL_PORT = 25

    # Uncomment and populate with proper connection parameters
    # for enable github login/singin.
    #GITHUB_API_CLIENT_ID = "yourgithubclientid"
    #GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"
```

**/home/ramos/taiga-front/dist/js/conf.json**
    
    {
        "api": "http://10.1.10.151:8000/api/v1/",
        "eventsUrl": "http://10.1.10.151/events",
        "debug": true,
        "publicRegisterEnabled": true,
        "feedbackEnabled": true,
        "privacyPolicyUrl": null,
        "termsOfServiceUrl": null,
        "maxUploadFileSize": null,
        "gitHubClientId": null,
        "contribPlugins": []
    }

**And in case the problem is in the nginx config**
**/etc/nginx/sites-available/taiga**

```
    server {
    listen 80 default_server;
    server_name _;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /home/taiga/logs/nginx.access.log;
    error_log /home/taiga/logs/nginx.error.log;

    # Frontend
    location / {
        root /home/ramos/taiga-front/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api/v1/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api/v1;
        proxy_redirect off;
    }

    # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }
}
```

**Comment by bameda** [comment]
Maybe the problem is in the configuration of taigra-front with the API url because the port is wrong

```
    "api": "http://10.1.10.151:8000/api/v1/",
```

Try with ```"api": "http://10.1.10.151/api/v1/"``` instead

**Comment by Eschin** [comment]
This is odd.  I'm trying to access the tiaga-front from two different machines, a windows 7 machine and a linux machine...

The Windows Chrome javascript console returns;
OPTIONS http://10.1.10.151:8000/api/v1/projects net::ERR_CONNECTION_REFUSED

The Linux Chrome javascript console returns;
OPTIONS http://localhost:8000/api/v1/projects net::ERR_CONNECTION_REFUSED

**Comment by Eschin** [comment]
I tried changing
   ``` "api": "http://10.1.10.151:8000/api/v1/",```
to
    ```"api": "http://10.1.10.151/api/v1/",```

I also saw that
    ```proxy_pass http://127.0.0.1:8001/api/v1;```
was set to port 8001 in the nginx config, so I changed it to
    ```proxy_pass http://127.0.0.1:8000/api/v1;```

Still no success.... I can access taiga-front from host, but not the other machines.
It's probably worth noting, I can access the backend api via http://localhost:8000/api/v1/ from the host itself, so the port should be 8000, if I'm understanding correctly...

Now both machines return...
```GET HTTP://10.1.10.151/api/v1/projects 404 (NOT FOUND)```

**Comment by bameda** [comment]
ok, so if you can access to the backend api via http://localhost:8000/api/v1/ you config.json file must have 
```
"api": "http://10.1.10.151:8000/api/v1/",
```

**Comment by Eschin** [comment]
SOLVED.

I had the production backend ports configured incorrectly.  Once I corrected it, I was able to access the default login page successfully from another system.

I appreciate the help, thanks :)

**Comment by bameda** [comment]
Great :dancers: :dancers: 

Thanks to you for using Taiga

**Comment by rpatni** [comment]
Hi..

I am facing the same issue. Can you please let me know what is the setup I need to do for the backend ports? I am using a VM on Azure and have created TCP end points for port 80, 8000 & 8001.

**Comment by sajjadrad** [comment]
@Eschin I have same problem for access to taiga from another pc in same network.Login page shows but post request sends to localhost:8000,how can I change localhost:8000 to my local server ip?

**Comment by superalex** [comment]
@sajjadrad it sounds like you taiga-front/dist/js/conf.json is pointing that url, did you try updateing it?

**Comment by sajjadrad** [comment]
@superalex Yup,nothing changed.I used taiga scripts and it works good.I think nginx config was the problem.

Thanks for answer.

**Comment by superalex** [comment]
Great!, 

You are welcome ;)

**Comment by mgrobelin** [comment]
Hello, due to evaluation setup I faced that problem too. http://taigaio.github.io/taiga-doc/dist/setup-production.html may lacks some explanations:


* taiga nginx vhost is meant to listen on myfqdn:80 (and optionally myfqdn:443 when SSL is wanted) as configured in /etc/nginx/sites-available/taiga (listen)

* that circus process manager listens on localhost:[5555,5556,5557] as configured in ~/circus.ini

* taiga API is expected to listen on localhost:8001 as configured in ~/circus.ini and /etc/nginx/sites-available/taiga (location /api & location /admin), which is quite confusing as the docs refer to localhost:8000 to test the backend

* ~/settings/local.py needs to have SITE configured to myfqdn(:80)

```
SITES = {
    "api": {"domain": "myfqdn", "scheme": "http", "name": "api"},
    "front": {"domain": "myfqdn", "scheme": "http", "name": "front"},
}
```

* postgres database server is expected to listen on localhost:5432 (why not localhost:5432 or even better unix domain socket /var/run/postgresql/.s.PGSQL.5432 ?) as configured in ~/taiga-back/settings/common.py ( and why is database not configured in local.py? what's the idea behind having local.py vs common.py?)

```
DATABASES = {
    "default": {
        "ENGINE": "transaction_hooks.backends.postgresql_psycopg2",
        "NAME": "taiga",
        'USER': 'taiga',
        'PASSWORD': 'XXX',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
```

* maybe it would be wise to bind postgres to localhost only: /etc/postgresql/9.3/main/postgresql.conf -> listen_addresses = 'localhost' -> service postgresql restart

* to verify final production setup, after starting up the services a `netstat -ntlp` should show at least this listening ports:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5555          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5556          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5557          0.0.0.0:*               LISTEN      -                      
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -                      
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      20350/python3.4 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -                
tcp6       0      0 ::1:5432                :::*                    LISTEN      -               
```

**Comment by Luyin** [comment]
change circus ip to 0.0.0.0.
127.0.0.1 is only for own pc.
It'll be work.

**Comment by superalex** [comment]
@Luyin if you are doing it you would be exposing the Taiga API to the external network in the port 8001. the idea is expose that port only internally and use nginx to expose the API ;)

**Comment by dan13373** [comment]
hi @all,

I have tried the same as above and followed the instructions at: http://taigaio.github.io/taiga-doc/dist/setup-production.html#_final_steps

I did not complete SSL but I did all other steps in details and checked twice. The backend at /admin is working perfect. The frontend does not load. Also ports 8000. @Eschin mentioned production ports configuration. Which ports must be changed?

Dan

**Comment by sthan001** [comment]
Guys not sure if this is solved already.
I ran under this problem and spent 1 day time [1 time investment though].

First is it looks like DNS problem to access taiga hostname from network lan[external to taiga server host/host outside taiga].
Example.
If DNS you picked is registed in network DNS entries then no problem - clients know where to connect for dns hostname [you used on conf files].
If NOT - temporary DNS name used for Taiga server then each clients[outside taiga server - local lan] to be added with hosts entry to know where to connect with front-dist libraries[java script].

Resolution for Non LAN DNS Entry usage for Taiga server:
Add below host entry
    192.168.17.39    taiga.tejas.com
        Linux: in your /etc/hosts File
        Windows: in your C:\Windows\System32\Drivers\etc\hosts or relative file based on OS version

Root cause Seems to Be the logs found in firebug.
[But these problem not occurs immediately takes time by the time you would have completely reinstalled your taiga! I let the browser in firebug mode for more time and captured below exception related to internal dns lookup fails from client browsers.]

Firebug Logs - Captured After say 30 minutes of idle client browser:
Firefox can't establish a connection to the server at ws://taiga.tejas.com/events.
app.js (line 2, col 18537)
WebSocket error: [object Event]
libs.js (line 11)
Firefox can't establish a connection to the server at ws://taiga.tejas.com/events.
app.js (line 2, col 18537)
The connection to ws://taiga.tejas.com/events was interrupted while the page was loading.
