### ISSUE TITLE
Enhancement: Mobile layout has some usability issues

### ISSUE THREAD

**Issue by fdenzer** [taigaio/taiga-front#436]
* Pinch zoom on login page scales text to unusable sizes

* left to right layout forces lots of horizontal zooming or scrolling on the user. This is especially true, if filters and submenus are stacked on each other

**Comment by Xaviju** [comment]
Hi @fdenzer ,

The team decided at the beginning of the project that Taiga will not be responsive because a Taiga mobile site does not has to have the same features as the full app and the look&feel should be focused on mobile interaction. When developing for mobile devices, we will focus on a more simple, mobile-friendly and fast app. At the moment, less than 5% of our users are coming from mobile devices and its not on top of our priorities at the moment but it is already in our backlog and, soon or later, we will focus on that.

It would be nice to know how do you imagine a Taiga mobile layout. What are the minimum required features when using a mobile device to make it as powerful as possible.

With your help, our 'mobile version' user Story will be better, so thanks for your help in advance. All information about how you imagine the app will be welcome. :)

**Comment by Xaviju** [comment]
We already  have a mobile User Story and we received some feedback from the community that some people is working on native apps so Ill close this to avoid repetition.
