### ISSUE TITLE
Option to remove weekends from the burndown chart

### ISSUE THREAD

**Issue by tdbs** [taigaio/taiga-front#470]
I think it would be useful for companies who don't work on weekends to have them out of the burndown chart, since it becomes misleading to have the work load distributed among days you won't effectively work.

**Comment by pinkra** [comment]
Absolutely! The burndown chart now is misleading because it assumes that points are burned also in the weekend!

**Comment by josedrac** [comment]
I also agree with this issue

**Comment by OpenNingia** [comment]
I also agree this should be implemented

**Comment by craiggunther** [comment]
Agreed as well. Great tool in all other respects!

**Comment by Perizote** [comment]
I also agree!

**Comment by davidperis92** [comment]
Yes, this would be a great feature.

**Comment by sergicollado** [comment]
Our team need this feature too!

**Comment by manudefrutosvila** [comment]
In my opinion this would be a great addition to such a good tool.

**Comment by videmort** [comment]
yes it should be implemented

**Comment by OpenNingia** [comment]
Jira Agile plugin (Greenhopper) does this in a smart way ( https://confluence.atlassian.com/agile/files/391087321/762876973/1/1436759811865/gh_burndown-chart.png ).

Notice how the ideal graph is draw.

**Comment by andresazp** [comment]
We would move whole organizations to taiga if this was available, as most of ours sprints are longer than a week and, like virtually anyone, we don't work 7 days a week

**Comment by jguitar** [comment]
What's the status of this? Is it planned?

**Comment by superalex** [comment]
Sorry, still no plans for it

**Comment by jguitar** [comment]
I'm working in this feature applying a patch to `taiga-back` code. Is there a nice way to add this behavior? I've been looking into the plugins but I couldn't see any place where override some code at `taiga-back` project.
My last try can be generate a new endpoint, and override the graph directive. But I guess it will result with duplicate code.

**Comment by fxfitz** [comment]
It would be *great* if we could get this in.

**Comment by jguitar** [comment]
![image](https://cloud.githubusercontent.com/assets/761794/25651471/8cb3bcde-2fe3-11e7-8500-2729f87b130a.png)

This is a preview, removing weekends and holidays (e.g. May 1st), I made it changing `taiga-back/taiga/projects/milestones/models.py`

**Comment by derwolfe** [comment]
It is beyond disappointing to see "no plans" in response to a user request that's nearly two years old. Really? No plans? Do you not have a product roadmap? Is this not a story on your **own** taiga board? If not, why not? If yes, surely you can provide some guidance on when (what appears to be, but may not be) a small request like this could be available to the paying customers who would really appreciate it?

**Comment by josedrac** [comment]
In our team we are developing a plugin so that the burndown wouldn't take
into account the weekends,
and also so that we could introduce the bank holidays so that they are not
taken into account either.
Juan F. is developing it, although we don't belong to Taiga. When this
development is completed
our idea is to make a pull-request to the Taiga's repository or we will
release the code to be used by anyone.

2017-05-03 17:54 GMT+02:00 Chris Wolfe <notifications@github.com>:

**Comment by superalex** [comment]
Thank you very much @josedrac ;)

**Comment by hdave** [comment]
If you do implement this, please make it an option.  We have people around the world, and others who work during the weekends.  I really like the way it works now.

**Comment by zeg-io** [comment]
@josedrac Any status on the plugin?  My team is wanting this too

**Comment by santiag** [comment]
Hi @jguitar did you have the plugin working? i just recently started with taiga and i am here by the question: how to remove Saturday and Sunday from Burndown chart

**Comment by andyrhubbard** [comment]
Hi everyone, this has been bugging me too. I'm not a python programmer so apologies if this is messy/wrong but this is my attempt to exclude weekends. 

Just copy this over the taiga-back/taiga/projects/milestones/api.py

(I haven't tested it massively to use at your own risk :))

[api.txt](https://github.com/taigaio/taiga-front/files/2623975/api.txt)

**Comment by qdouasbin** [comment]
> 
> 
> Sorry, still no plans for it

Hi there,

It's almost 2020 and this issue has been opened since 2015!

Have you any plans to include this feature in a future release?

The burndown chart is misleading if this feature does not exist.
My team and I moved to scrum management in order to have this great diagnostic and we feel very frustrated that Taiga overlooks this important aspect...

It honestly does not seem like a lot of work.

Can you test the `api.py` script above? 

Good luck!

**Comment by qdouasbin** [comment]
> 
> 
> Hi everyone, this has been bugging me too. I'm not a python programmer so apologies if this is messy/wrong but this is my attempt to exclude weekends.
> 
> Just copy this over the taiga-back/taiga/projects/milestones/api.py
> 
> [api.txt](https://github.com/taigaio/taiga-front/files/2640538/api.txt)
> 
> (I haven't tested it massively so use at your own risk :))
> 
> ![weekends_off](https://user-images.githubusercontent.com/4704658/49146135-69c38580-f2f9-11e8-84bd-a57209c178fc.png)

Hi Andy,

It's been a year now. Did you find any major problem with your `api.py`? 
Do you consider submitting a pull request?

Thank you for your work!

**Comment by andyrhubbard** [comment]
Hi,

Yes my team have been using it without any problems. 

I haven't considered submitting a pull request as I believe it needs better integration so it can be fully  customised in the settings.

**Comment by basjes1977** [comment]
Hi I have been testing with 6 and guess what ...
This feature request seems to be not incorporated. 
Could you please make an option to in or exclude weekends?

**Comment by aleurent33** [comment]
Hi,

Yes, unfortunately, the need has not been taken into account for the new version.
For information, I have just retrieved the api.py file provided above to integrate it in our server to take off weekend days from the burndown chart. I am going to test it as soon as possible.
From the script provided, there is a small mistake on the first iteration because the amount of point for the first day does not correspond to the total amount but there is already a substraction.

Here is a diff of my changes to apply on file /opt/taiga/app/back/taiga/projects/milestone/api.py

--- api.py  2022-02-08 16:47:00.768968047 +0100
+++ api-1644336398020.py    2022-02-08 17:06:38.035065148 +0100
@@ -122,21 +122,41 @@
         current_date = milestone.estimated_start
         sumTotalPoints = sum(total_points.values())
         optimal_points = sumTotalPoints
-        milestone_days = (milestone.estimated_finish - milestone.estimated_start).days
+        milestone_days = self.count_weekdays(milestone.estimated_start, milestone.estimated_finish)
         optimal_points_per_day = sumTotalPoints / milestone_days if milestone_days else 0

         while current_date <= milestone.estimated_finish:
+
             milestone_stats['days'].append({
                 'day': current_date,
                 'name': current_date.day,
                 'open_points':  sumTotalPoints - milestone.total_closed_points_by_date(current_date),
                 'optimal_points': optimal_points,
             })
+
             current_date = current_date + datetime.timedelta(days=1)
-            optimal_points -= optimal_points_per_day
+            if self.is_weekday(current_date):
+                optimal_points -= optimal_points_per_day

         return response.Ok(milestone_stats)

+    def count_weekdays(self, start, finish):
+        count = 0
+        current_date = start
+
+        while current_date <= finish:
+            if self.is_weekday(current_date):
+                count += 1
+
+            current_date = current_date + datetime.timedelta(days=1)
+
+        return count
+
+    def is_weekday(self, date):
+        weekno = date.weekday()
+
+        return weekno < 5
+
     @detail_route(methods=["POST"])
     def move_userstories_to_sprint(self, request, pk=None, **kwargs):
         milestone = get_object_or_error(models.Milestone, request.user, pk=pk)

Hope it can help.
Thks
