### ISSUE TITLE
I can't add a new member

### ISSUE THREAD

**Issue by SaulBurgos** [taigaio/taiga-front#536]
Hi , today I found the new update on taiga.

But I can't add a new member to the project. I write the email and when I click "create", nothing happen , just stay there loading...

Thanks

**Comment by mnelson7982** [comment]
I am experiencing the same.  The Member Role dropdown does not seem to be bound by any array.

**Comment by bameda** [comment]
Sorry, I got it. I'll try to fix asap.

**Comment by bameda** [comment]
Fixed

**Comment by bameda** [comment]
@mnelson7982 @SaulBurgos Could you test it?

And If you have problems to see the role selector it's probably because of your cache. If you are using chrome I had to use this method for really cleaning it for tree.taiga.io domain:
 - press F12
 - right click on the reload button of the navigation bar
 - empty cache and hard reload

Firefox and other are less cachemaniac and you can clean cache easier :)

**Comment by mnelson7982** [comment]
yeah. all is well :) thanks for the rapid response.

**Comment by bameda** [comment]
:smiley_cat:

**Comment by SaulBurgos** [comment]
Fixed Thanks
