### ISSUE TITLE
Links not working from timeline when project-slug is changed

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#538]
I changed the project-slug some time ago (before the timeline was introduced)
Now when I click in the timeline on a link to a wiki-page of US, I get a 'page not found'

**Comment by superalex** [comment]
You are right @florisvanwoudenberg, could you write to support@taiga.io with your project details so we can regenerate your timeline?

Regards!,

**Comment by florisvanwoudenberg** [comment]
It's a self-hosted instance :-)

**Comment by superalex** [comment]
Sure!, you should use the command rebuild_timeline with something like:

```
python manage.py rebuild_timeline --project PROJECT_ID
```

From taiga-back

**Comment by florisvanwoudenberg** [comment]
Thanks, it worked. I used the command without --project to regenerate the timeline global.
Is there a possibility to add a button to the project config page to regerate the time-line? Or even better, to automatically regenerate it after changing the project-slug?

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

We have disabled the changing slug feature because of the side effects it could have (a super admin user could always use the django admin for updating the project slug)

About adding the button for regenerate: if you have a big project it's a bit hard for the machine to do it so we should throttle that kind of requests, we should think about it carefully. As a first approach we thought a management command should be enough but may be it isn't.

Regards!,

**Comment by florisvanwoudenberg** [comment]
I checked it and see that indeed I cannot enter my own project-slug. I use this for a short reference to US and task outside taiga (slug-#id) so an ugly slug (username + project-title) is not preferable.
(See https://github.com/taigaio/taiga-back/issues/321)

**Comment by superalex** [comment]
I understand @florisvanwoudenberg, but you still could use the django admin interface for updating the slug if you need to do it.
