### ISSUE TITLE
Adding points to tasks

### ISSUE THREAD

**Issue by geoah** [taigaio/taiga-front#569]
I'm trying to figure out if its possible to add US points to tasks.
The closest thing I can find is custom fields.

This unfortunately isn't optimal as creating a custom field for us points doesn't define the team for which it is for and requires someone to go through a list of tasks and sum up points for each team.

If the reason for this feature not being implemented is time constrains then I could try and figure out how to implement it (I suck at python but owh well).
If on the other hand not implementing the feature was a intentional decision then I'll just close the ticket and leave it at that! :)

Thank you all for a wonderful tool.

**Comment by bameda** [comment]
Yes, it was a intentional decision: It's more easy and gives me more value estimate a US (a new functionality/feature). A task is a pice of work that has no value by itself [1] [2]

However I created a petition to the team consider your proposal

https://tree.taiga.io/project/taiga/issue/3027

Thanks.


[1] http://www.mountaingoatsoftware.com/blog/the-difference-between-a-story-and-a-task
[2] https://blog.taiga.io/user-stories-demystified.html

**Comment by mikaoelitiana** [comment]
Hello,

I am also really interested to have this feature. In our use of Taiga, it makes more sense to asign points to tasks instead of US. @bameda You mentionned a petition, can I find this online and participate or it's internal in the project team? 

Thanks

**Comment by bameda** [comment]
Is online https://tree.taiga.io/project/taiga/issue/3027 and you can upvote it.

**Comment by mikaoelitiana** [comment]
Thanks!!

Le lun. 6 juin 2016 12:48, David Barragán Merino <notifications@github.com>
a écrit :

> Is online https://tree.taiga.io/project/taiga/issue/3027 and you can
> upvote it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/569#issuecomment-223914333>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApLa40Rpg4nh5L6dkxltUYatAHI12ipks5qI-zhgaJpZM4FT0ud>
> .
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name

**Comment by eddie-dunn** [comment]
I don't see why tasks cannot be assigned points. We are using the Scrum view in Taiga, and have defined and point estimated a couple of user stories. Many times, while working on a user story, the story is delayed by an addition of a task, which is OK. The problem we have right now, however, is that we are on the last day of a sprint and our sprint velocity is zero because none of the stories have been fully completed, though most of their tasks are closed.

How are we supposed to gauge our _actual_ sprint velocity when we cannot assign points to individual tasks?

In my view, only being able to assign points to a user story is too coarse, and the only alternative I see is to make extremely granular user stories (i.e., in essence: tasks), each with a simple task called "complete me" which we move as the user story progresses. That seems quite ineffective to me.

**Comment by eddie-dunn** [comment]
I quite like the proposed solution in [this post](https://groups.google.com/d/msg/taigaio/TetNN8sqVZU/SG6JSg1nFQAJ).

**Comment by EllisShen** [comment]
I very like this proposal and wish it get implemented asap.

Our team uses Taiga everyday. The problem we face constantly is that we want the burn down chart reflects the actual digest of each task of User Story. Let's say if I can a pretty big story contains 5 different tasks, the Scrum Master won't like to see that the Burn down chat didn't change for a couple days until all five tasks get resolved.

Furthermore, I like to see that User Story Point can be sum up automatically according to all tasks belong to the story.

**Comment by robbroadwell** [comment]
I would also appreciate this. Keeping track of points at the task level makes more sense for my projects.

**Comment by durgaswaroop** [comment]
If this feature is not implemented why does the Sprint task board on the mobile app has a points display?
It just shows `? PTS` for now as there is no way to add points. But you could have added the functionality before giving a display for it.

**Comment by bameda** [comment]
@durgaswaroop the Taiga team has not developed the mobile client, it has been the community (http://www.techfunder.de/ in this case) You can find more info here http://www.taigaapp.com/

**Comment by durgaswaroop** [comment]
Oh. My bad.

**Comment by leggettc13** [comment]
I agree with several people on here about being able to assign points at the task level. For larger stories that need to be broken up into several tasks, only being able to assign points at the User Story level makes it look like we didn't do anything until the end of the sprint according to the burndown chart. Since my particular team is a group of college students working on a tight deadline we have shorter sprints so this happens somewhat often. Our instructor also examines our burndown charts so it looks bad on us when it looks like no points have been taken off until late into the sprint. I quite like Taiga in general but this issue is a bit aggravating to get around.

**Comment by pengwang823** [comment]
Hi, guys:
I used taiga in my team and found this is issue is definitely a problem for me, so I just did some hack work, although it's not perfect but satisfy my needs, it has some bug like you have to calculate task points according to user story's upper-bound, Hope this patch can merged in official build in near future.
[Uploading points.zip…]()

**Comment by ThaJay** [comment]
very nice. Maybe open a pr?
Also, what do you think of having US points calculated by adding task points?

**Comment by pengwang823** [comment]
Maybe,  I consider to have a pr, however, no time to have qa, if someone help to add testing case, appreciate. For the second question, I dont think so. Because task points is updated by task owner. us points is estimated by product owner, So task owner should not.

**Comment by neoecos** [comment]
Is there any development on this issue?

**Comment by diacritica** [comment]
I am picking this one for review for the next major release (@pengwang823 contribution), sorry it took so long. The problem with this feature request is that it's probably several feature requests after the long thread.

**Comment by allanlegalstart** [comment]
@diacritica  @pengwang823  , any news on that front ? 

for the problem itself i understand @bameda  that in a perfect world the purist view of "task have only value has a whole"
but there's so many situations (user story longer than one sprint, user story spread on several people and each of them being able to estimate their specific tasks etc.)  where having points on task would permit to be more pragmatic  (and purist would still be able to restrict themselves)
