### ISSUE TITLE
Backlog: Resize width of issue list and Spring manager

### ISSUE THREAD

**Issue by walljm** [taigaio/taiga-front#579]
Because the only place you can move items from sprint to sprint or backlog to sprint is the backlog page, the width of the sprint list is hard to use because it cuts off the titles in the sprints.

**Comment by shrift** [comment]
I believe you mean "sprint" not "spring".

I agree, I would like to be able to resize, or hide, that Sprints column of the backlog so that I can reclaim that space for reviewing my backlog. I would particularly like to be able to just hide or remove the Sprints column as I am not using them. I enabled the backlog because that format is more conducive to creating and reviewing a backlog.

**Comment by superalex** [comment]
Hello @shrift 

We had an existing enhancement request for customizing the backlog columns here (https://tree.taiga.io/project/taiga/issue/3035), I've just added your comments there too :+1:

**Comment by shrift** [comment]
Thanks!

**Comment by superalex** [comment]
You are welcome! ;)
