### ISSUE TITLE
As a scrum master I want to keep track of meetings

### ISSUE THREAD

**Issue by maci0** [taigaio/taiga-front#622]
It would be good if there was a section where you can log meetings, especially the recurring ones you usually have in scrum.

You should be able to set what kind of recurring meetings you have (Sprint Planning Meeting, Daily Scrum Meeting, Sprint Review Meeting, Sprint Retrospective Meeting by default) how long they take (with sane defaults) who will attend or has attended should be there as well and optionally the content (useful for online teams that use IRC to do their daily scrum etc)

This would also be a great way to document customer feedback from the sprint review etc.

**Comment by superalex** [comment]
Thanks for your feedback and ideas @maci0  :+1:

**Comment by allan-simon** [comment]
+1 it would make a lot of sense as a module  one can activate / deactivate on a per project basis.

**Comment by ssbarnea** [comment]
As someone that started to use Taiga for Scrum two months ago I still feel that the lack of support for keeping track of restrospective meetings with the standard columns a serious downside. 

Because of this we now use two systems (Taga + Trello) instead of one.

Standard retrospective columns (for each sprint):
* Previous actions
* Facts
* Good Things
* Bad Things
* Ideas for Improvement
* Feelings
* Actions
