### ISSUE TITLE
As an admin, I'd like to add users manually from my interface

### ISSUE THREAD

**Issue by mixedCase** [taigaio/taiga-front#647]
At the moment I don't see an easy way to create new users without enabling public user registration. This is inintuitive considering the existence and name of that toggle.

**Comment by superalex** [comment]
Hello @mixedCase 

If you have your own instance you can create them using directly the django admin. It will be probably a /admin url depending on your web server configuration.

Regards!,

**Comment by mixedCase** [comment]
Could we have a link to the Django admin UI from the Taiga admin UI?

I didn't know that panel existed.

**Comment by superalex** [comment]
We thought it wasn't a good idea for the general users having that panel, you could really break your Taiga instance if you use it badly and only superadmins (not just project admins) should have that link so we thought it wasn't a good idea having it on the interface. I think we should make it more explicit in the documentation.

**Comment by eeriksp** [comment]
The admin URL seems to the `/admin/` (the last backslash is important, too).
However, I got `403 CSRF verification failed. Request aborted.` when I tried to log in.
I guess I should modify the variable for the Docker container to get it work.

**Comment by bameda** [comment]
Hi @eaposner

This is because you are running your instance over http instead of https. You have to change the settings to access to the admin panel in this case. 

If you run taigran without docker, change this in your settings/conf.py
```
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False 
```
And restart taiga-back services.

If you run taiga with the docker instance follow this https://github.com/taigaio/taiga-docker/issues/20#issuecomment-771600544

And one more thing, run a production environment over http is not highly recommended, we  would suggest securices your instance.

Best regards
