### ISSUE TITLE
Feature request: Remove username from project slug

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-front#652]
As discussed with @superalex just now, this is a feature request to remove the username portion of the url slug for a project. It looks quite weird to customers when their project url is prepended with the username of the person opening the project. If some kind of identifier is needed to make the url unique maybe a project shortname or set of characters could be requested when creating a project?

**Comment by kabaka** [comment]
Agreed.

It only took about an hour after setting this up for someone to ask me why my name was on every URL.

**Comment by kabaka** [comment]
The more I think about this, the more I realize that some kind of prefix is probably necessary. I feel like the most ideal fix would require support for organizations, so that the organization name could be used as the prefix. I did't see an open request for such a feature, so I have added it as #653.

For self-hosted projects, which I believe this ticket really refers to, this should probably be some kind of configuration option system-wide. Otherwise, the Django admin interface does a good job of letting us edit slugs.

**Comment by H3Chief** [comment]
+1

**Comment by zacbri** [comment]
+1

**Comment by vibhor-trantor** [comment]
+1

**Comment by Mr-Snailman** [comment]
+1

**Comment by fabue** [comment]
+1

**Comment by kaazoo** [comment]
+1

**Comment by vibhor-trantor** [comment]
+1

**Comment by neomilium** [comment]
+1

**Comment by cyberdie** [comment]
+1

**Comment by herbsmn** [comment]
+1

**Comment by stevenroose** [comment]
There should be a `slug-template` field in the admin panel that defaults to `"%u-%n"`, but that can be changed to just `"%n"`.

**Comment by herbsmn** [comment]
@stevenroose can this be done manually right now?

**Comment by stevenroose** [comment]
@herbsmn You can change the slugs individually... I did that for the
projects I created. It's in the admin panel at
https://your.taiga.site/admin/ (mind the ending slash).

**Comment by herbsmn** [comment]
this is super helpful @stevenroose! I didn't even know about the admin panel!

**Comment by herbsmn** [comment]
looks like you have to do this slug name change before doing stuff in projects or else it will break some links.

**Comment by stevenroose** [comment]
Yeah, if you have any links to the projects in which the slug appears, you
should watch out changing it. Btw, make sure you change the admin password
for the admin dashboard. I guess a lot of users don't know about the
dashboard and still have the admin/123123 active, which is really dangerous.

**Comment by herbsmn** [comment]
@stevenroose yeah, that's a pretty big security problem having people not know about this. I luckily changed my admin password right away even though I didn't know about the admin panel at the time. I assumed something like that existed though.

**Comment by stickyhands** [comment]
after you changed the slug you have the regenerate the projects timeline:

`python manage.py rebuild_timeline --purge`

**Comment by bameda** [comment]
@stickyhands there is a console command to change the project slug

```bash
usage: manage.py change_project_slug current_slug new_slug

Change the project slug from a new one

positional arguments:
  current_slug          The current project slug
  new_slug              The new project slug
```

**Comment by neknalb** [comment]
+1

**Comment by laszlo-apro** [comment]
Hi guys,

I'm wondering if there is any update on this fairly old thread? It's a serious issue, and I presume a lot of us want it to be solved as soon as possible. It looks really unprofessional having the project creator's username in the URL.

Hope you will come up with a solution in the near future.

Regards,
Laszlo

**Comment by rastapopougros** [comment]
+1 and more, it's so damn weird! :) 

The goal of a project manager like taiga is to work… with your team. Like… always. So it doesn't make sense to have the name of one person in the URL. :D.

The new project is almost always for everyone, and maybe few months later, the person who created the project will no more work on it…

"- Hey come work with us for SuperClient in the project : ourtaiga.org/project/charlie-superclient/timeline
- Ok thanks. Eh who is Charlie ?
- Hum, don't know… Maybe I remember a guy working here in 2003…"
:D

**Comment by rastapopougros** [comment]
Also, to be a bit more constructive, the ergonomic solution is very simple : provide an explicit field to define the project slug in the creation form.

When the user enters the project **human** name, the slug could be pre-generated (with a prefix/suffix or not). But it can be modified.

And when the user submits the form, there is a validation for this field, checking not already used, and error message if that's the case.

**Comment by dhruv-bansal** [comment]
hey everybody, any update on this thread. Can I remove the username from my git repo project URL?

**Comment by tanc** [comment]
There are currently two methods I know of, if you have a self-hosted instance:

Method 1:
Visit the admin panel at https://your.taiga.site/admin/ (mind the ending slash)
Click on Projects link under Projects section
Click on your newly created project
Edit the Slug field and save the project

Method 2:
Use the console command:
```
usage: manage.py change_project_slug current_slug new_slug

Change the project slug from a new one

positional arguments:
  current_slug          The current project slug
  new_slug              The new project slug
```

It has been five years since my original request but as far as I can tell only @bameda from Taiga has replied with a solution (useful only if you have server access). It would be good to hear from the devs about whether this is something in scope for a future release and if not why they don't want to implement it.

**Comment by rastapopougros** [comment]
We use the first method since our start with Taiga, but it's obviously technical and anti-ergonomic :)
That's why I suggested to have a pre-generated slug field directly inside the normal new project form, with a unicity test on it (and that's the way Drupal or other systems manage the slugs : never hidden).

To go in this direction, an other argument : some could say "slug is a technical thing, we don't want to see that in an interface". And that's **totally wrong**. Slug is used in all URL and sub-URL of the project. And URL is the very first thing all end-users see of a place on internet. It's one of the first thing you learn when you study ergonomy and UX : there is not only the final interface, but how users find the place before. It's this URL anyone copy and paste in messages to others "hey my friend, watch how we work in our super projet here : …".

So because URL is important, slug is important, and then it must not be hidden but it must be chosen explicitly in the create form.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and after the launch, we’ll come back to this issue as it’s part of our roadmap. This time we will make sure to review it properly. 

Thank you very much on behalf of the Taiga Team!

**Comment by tanc** [comment]
@NatachaMenjibar just politely checking in now that Taiga 6 has been released. I wanted ask if this issue is going to be addressed soon? Congrats on the Taiga 6 release btw!

**Comment by tanc** [comment]
Also to note, for future me, the new method to change the slug when hosting Taiga 6 with Docker:

```
docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage change_project_slug [current_slug] [new_slug]
```

**Comment by yamila-moreno** [comment]
Hi !

@tanc currently it's more confortable to use `taiga-manage.sh` for this kind of commands

About the main topic, in an on-premise instance you can configure the behaviour of the slug. We're going to expose this configuration near soon.

Meanwhile, you can whether use the advanced configuration and map it a `config.py` with this variable:
 ```python
# Setting DEFAULT_PROJECT_SLUG_PREFIX to false removes the username from project slug
DEFAULT_PROJECT_SLUG_PREFIX = True
```

or change_project_slugs and wait for the new version.

Cheers!

**Comment by rastapopougros** [comment]
It's a good thing at least if there is now a config to don't add the username in the slug.

But I as said : "So because URL is important, slug is important, and then it must not be hidden but it must be chosen explicitly in the create form." (and that means : not in obscure terminal command : integrated in the interface). So I will also wait a version which let that :) 

(anyway I first have to upgrade my 5 instance to 6…)
