### ISSUE TITLE
random watchers appear in notifications when modifying user stories

### ISSUE THREAD

**Issue by kabaka** [taigaio/taiga-front#658]
Example from Slack notification (I don't believe [taigaio/taiga-contrib-slack](/taigaio/taiga-contrib-slack) is at fault here):

![image](https://cloud.githubusercontent.com/assets/278887/10293036/ff4c5be8-6b77-11e5-94e0-33425c45bfa6.png)

To cause this, all I did was drag a user story on the kanban page from one status to another. Watchers should never have been changed. When looking at the user story detail page, the new Cassie is not present.

Earlier, I commented on another story on which I am a watcher. A different Kyle was shown in the watchers change list for that, even though (1) we do not have anyone with such a name on our team and (2) I did not modify the watchers list in that change.

It looks to me like different users with the same first name are being found and shown in this list.

I can only hope these other people are not receiving notifications from our private project.

--

Please let me know if I should move this issue to taiga-back. It seems like taiga-front is kind of a catchall for issues right now. ;-)

--

Edit: It seems that the same users are also shown if including an @ mention of a user. For instance, mentioning our Cassie resulted in the same Haffner being shown in the new watchers list on an issue which has no watchers at all.

**Comment by superalex** [comment]
Hello @kabaka,

Actually you can add as a watcher to any taiga user if you use the @username in a comment, as Rylee commented using @kyle that user was added to the us watchers but:
 - Only team members are notified so this external user isn't receiving any notification about your project
 - The web app only shows the user watchers that are members from the project

This is actually working like this because we are working on a feature that will allow users watch/like items from different projects, with the new release this watchers part will have a much more understandable.

Thank you very much for reporting and sorry for the inconvenience!
