### ISSUE TITLE
Clicking outside the search field should probably close the overlay

### ISSUE THREAD

**Issue by marnovdm** [taigaio/taiga-front#727]
Now I have to press escape or click on the x in top right. Most websites close such overlays on clicking 'outside' of the overlay. Maybe this could be implemented in Taiga as well?

**Comment by Xaviju** [comment]
We decided not to implement this option because it could easily lead to mistakes since there is no obvious way to do that if we want to keep the full page overlay (and we want to keep it). We decided to implement the ESC button so advanced users have always a fast command and the UI will keep using the cross.

**Comment by marnovdm** [comment]
Thanks for the feedback!

**Comment by Xaviju** [comment]
Thank YOU!
Please keep sending your UX enhancement proposal, we are happy to receive them.
