### ISSUE TITLE
Done/Archived SU need visual cue in backlog

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#743]
It's hard to tell at a glance whether a SU needs action or not.

**Comment by superalex** [comment]
Hello @mkaito 

Sorry but I don't really understand the reason after this enhancement. In the backlog screen the done/archived user stories should be associated to a sprint and in this situation they are marked in a different way if they are in a closed status. 

In the left column the status for each user story is shown in the color they have.

What kind of visual cue are you missing?

**Comment by mkaito** [comment]
![2015-11-24-134154_1920x1080_scrot](https://cloud.githubusercontent.com/assets/20434/11368344/32cdc8ca-92b1-11e5-8077-29d78c277d01.png)

**Comment by Xaviju** [comment]
Sorry, this is not an enhancement. In the backlog view, if a User Story gets archived it already has its status to make it recognizable. You can change the color of the status if you need to improve the archived color to make this status more recognizable.
For your workflow, I strongly recommend you to use kanban, since its UI makes a lot more sense. The backglog view is intended to be the page to prepare sprints, not to close Stories and for the screenshot seem that you are not using sprints.

**Comment by mkaito** [comment]
Kanban use is sadly limited by it not being able to work with tasks.

**Comment by Xaviju** [comment]
So you are looking for the taskboard view. If you create an sprint you will be able to go into the taskboard view which a task view area. You are currently working between both.

**Comment by mkaito** [comment]
I'm starting to think that half of my "problems" with taiga are due to a miscommunication or lack of documentation about how taiga is meant to be used. Your docs say taiga is intuitive and doesn't need extensive documentation. I think I disagree :stuck_out_tongue:

**Comment by bameda** [comment]
Is intuitive if you know about Agile methodology. 

And if you use kanban you can divide stories in task too in the story detail page.

**Comment by mkaito** [comment]
Sure, but then those tasks are effectively hidden "from outside". Kanban is about visualizing progress, and hidden tasks do not follow that ideal.

Maybe I'm missing something, but as far as I can tell, tasks are only visible in a sprint's task board and in their parent story's detail page. That makes them useful in sprints, but useless for a kanban workflow.

I'm admittedly new to this scrum and kanban stuff, but I found Jira Agile easier to use, and that's saying something.

**Comment by Xaviju** [comment]
We have some improvements for the tasks in the kanban, but you are right, in Kanban taks are hidden by default because Kanban is supposed to be used at a Story level. Since some users asked for it, we have an open enhancement and we are working on it (you can view our UI cards refactor in our kanban). In any case, support@taiga.io and the mailing list is always ready to answer your questions.
We are sorry if you find another tool easier to use, we are working hard to improve Taiga everyday.

**Comment by mkaito** [comment]
> we are working hard to improve Taiga everyday

And I'm trying to help by giving feedback :wink:

**Comment by Xaviju** [comment]
Yes, thanks for your feedback! :tada:

**Comment by mkaito** [comment]
> Kanban is supposed to be used at a Story level

Kanban does not have a concept of story. Stories are Scrum artifacts. Kanban just has "stuff" that needs to be done, organized in a prioritized stack.

My confusion came from the fact that you use a scrum entity, with scrum functionality, and put it on a kanban board. **Tasks** are specific to the scrum workflow implemented in Taiga, but they are not disabled for a kanban workflow. In kanban, all entities are equal, and so one should be able to manage all entities equally on a board. Think of it as different post-it colours to denote different kinds of cards.
