### ISSUE TITLE
Hitting ESC in a text input field

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#744]
In any overlaid text input field (like when editing a wiki page), hitting escape will dismiss the text input field and lose any changes. As a vim user, I'm going up the walls.

Either make this optional, or keep whatever was typed in local storage so it's still there if I edit the same place again.

**Comment by Xaviju** [comment]
Hi @mkaito this is an expected behavior of the UX in most of the websites. Hitting escape should undo your changes in an input field. We have an open enhancement to add a reminder that you will lose data if you close the input, so Ill close this and keep the other on Taiga.
https://tree.taiga.io/project/taiga/issue/3370

Remember: You can upvote it in Taiga to raise its importance.

**Comment by mkaito** [comment]
I seriously think the contents of a textarea should be saved, just in case. Worst case, you can add a "revert changes" button, in case a user *actually* wants to dismiss whatever he wrote.

I'm sorry, but a reminder is no excuse to willingly dismiss content. Github and reddit do this, even between page loads, and it is greatly appreciated.

**Comment by Xaviju** [comment]
Sorry, with 'a reminder' I mean an alert box warning you that if you accept you will miss your data, something similar to what facebook does. Do you think isn't that enough?

**Comment by mkaito** [comment]
Oh that would be enough.

**Comment by Xaviju** [comment]
Thanks @mkaito

**Comment by marton78** [comment]
This is madness and clearly **not** expected behaviour. Recently when writing a long user story during a baklog refinement meeting, I typed a `#` and wanted to dismiss the appearing suggestions with ESC. Boom, there go ten minutes of work! Please add an "are you sure you want to leave this" dialogue box **iff** the contents of the text box have changed.
