### ISSUE TITLE
Different background for user stories lanes in sprint taskboard

### ISSUE THREAD

**Issue by pinkra** [taigaio/taiga-front#752]
As developer i want to see different background colors for completed, done and in progress user stories lanes in the sprint taskboard, so i can identify quickly what user stories aren't finished yet.

**Comment by superalex** [comment]
Thanks for the feedback @pinkra we will review it with our UX/design team.

Regards!

**Comment by pinkra** [comment]
You're welcome! Regards!

**Comment by Xaviju** [comment]
We made some tests and it leads to a lot of visual confusion between cards, tags and lanes even with desaturated colors. We found that the information of the color lane is already given in the top bar and can be set by the user. We want to avoid color bloating the kanban/taskboard screen.

Otherwise, there are no completed, done, and in progress status only. Those status can be set in the admin area and assigned to any color which could cause many confusions between colors.  

Sorry, but we will not include this in the Taiga core for the moment.
