### ISSUE TITLE
There is no option to add estimation for a issue

### ISSUE THREAD

**Issue by ranjur** [taigaio/taiga-front#756]
We have option to add points in a user story, but no option to add same for an issue.

**Comment by superalex** [comment]
Hello @ranjusayonetech 

We are not big fans of estimations for issues, if one of your issues is so big you could use the "promote to user story" so it works with the standard user story workflow.

**Comment by allan-simon** [comment]
+1 @ranjusayonetech ， what if i have lot of bugs, they don't belongs to user stories, but i still have to estimates for this cohorts of bugs. or issues to track each piece of technical debts , you want to have an estimate about them to know "how long would it take to solve them" , especially you want to know for the small one , so that you can insert one or two into a sprint.
