### ISSUE TITLE
How to talk to the users

### ISSUE THREAD

**Issue by dstahlmann** [taigaio/taiga-front#871]
After you closed #869 I take a few minutes to have a look over the translation file. Sadly I'am new to github and havn't found a way to contact you in private @bameda 

During the review I recognized a different way the german translation (I'am a native speaker) is talking to the users.

In Germany we have two diffenrent ways to talk to people:
1. "Sie" it's the polite and 'respectfull' way you talk to strangers or e. g. your bank employee, the guy who sells you a car or your teacher. From company to company you also have to "siezen" (the it's called in Germany) your boss.
2. "Du" is the friendly way. You may also respect the other one, but the you show you like each other. It's the way you usually talk to your friends, girlfriend, child (your own and often young others), colleagues or your mates ( also if you not know each other very well, but you are mates :-D )

Wich way you want to have in TAIGA? I would search and replace all "Sie" or "Du" when I have time.

The other question is if your "Oompa Loompas" are meant as an proper name, or if they should be translated. For germany it was: "Helferlein"
By looking into the translation file I found both. Do you prefer "Oompa Loompas" or "Helferlein"?

**Comment by bameda** [comment]
Hi @dstahlmann, to contact with the Taiga Team you can use the support email (support@taiga.io), the Taiga mailing list (https://groups.google.com/forum/#!forum/taigaio). You can find more info at https://taiga.io/support/how-i-do-stay-in-touch-on-the-latest-news/.

Concerning the translation you choose. Taiga is an open source software and the community has translated it to the different languages. The Taiga Dev Team can contribute to english, spanish and catalan because are our native languages so contributions and recommendations from a native speaker are welcome.

I can tell you that in Spain we have two ways too, and we've use the most impersonal. Taiga is a project management app with which you are going to have a lot of good and not so good moments with it would be good you are friends soon ;-)

Oompa Loompas or Helferlein I don't know. We are going to change it in the future (https://tree.taiga.io/project/taiga/issue/3040) because 
It can be interpreted as something offensive (although it's not our intention, our oompa loompas are lovely and they are well cared).

**Comment by dstahlmann** [comment]
have submited a few more translated strings to the german translation file :-D

**Comment by bameda** [comment]
Thanks
