### ISSUE TITLE
Is there any way to archive a sprint?

### ISSUE THREAD

**Issue by holden-caulfield** [taigaio/taiga-front#883]
Disclaimer: we are relatively new to Taiga so there may be a related feature I didn't find that covers this.

We use taiga for a living project (in the sense it is an ever-improving product, instead of something that begins and ends). Therefore as time goes by the sprints accumulate on the right side of the backlog view.

It seems the only way I can take them out is to delete the sprints, which implies losing valuable information of what was done when. Is there a way to "archive/close/mark-as-done" a past sprint so it will not show on the right side of the backlog but still be reacheable somehow if we want to do forensics?

**Comment by bameda** [comment]
Hi @holden-caulfield 

One sprint is closed if all its stories are closed and one story is closed if all its tasks are closed.

![image](https://cloud.githubusercontent.com/assets/877218/13181667/72203fe6-d72e-11e5-811e-9741438c6622.png)

![image](https://cloud.githubusercontent.com/assets/877218/13181678/7a1f10d2-d72e-11e5-83c8-cce6f83447b5.png)

**Comment by raphaelyancey** [comment]
This is a problem as an issues-only sprint can never be closed, even if all the issues are closed.

**Comment by kaisbe** [comment]
I just wanted to help others who might still have the same issue I faced: a sprint that is not yet closed despite having all U.S in "Done" status.

There might have been **unfinished issues** on the sprint which are "Postponed" issues - they need to be moved to a next sprint, via the button "Move unfinished items to another sprint" (double-arrow logo) which is near the label "closed tasks", on the taskboard of the sprint that is supposed to be finished.

**Comment by ChrisG-BellTV** [comment]
I'm encountering the same issue mentioned by raphaelyancey above whereby it looks like the "completed points" calculations in Taiga have failed or been corrupted.  It never updates despite all tasks being done and closed with no open tasks.  I even tried to the "move the unfinished items to another sprint" function (double arrows button at the top) to another sprint and the issues seemed to follow these user stories.  I now have two sprints that aren't tracking the completed points properly and subsequently will not close.  This issue is very impactful and essentially negates the core Agile functions (sprints) of Taiga.  Does anyone have a fix for this issue?

**Comment by myii** [comment]
Workaround used to "close" the sprint:

* Added a dummy task to the `Storyless tasks`.
* Set its status to `Closed`.

You could probably combine both steps when creating the dummy task -- I'll try that the next time I come across this situation!
