### ISSUE TITLE
Events need adding to Issue Details, US Details, Task Details  pages

### ISSUE THREAD

**Issue by siliconalchemy** [taigaio/taiga-front#913]
There seems to be no events/realtime updates to the US Details or Task Details pages, so no updates to these pages get broadcast to other team members.  It should work as per the backlog page where all updates to the page are broadcast to other browsers through events/websockets.

**Comment by yomguy** [comment]
Event updates could also include all comments in those detail pages (like on GitHub). This would be useful to avoid discussion discontinuities and too many page reloads.

**Comment by zaleb** [comment]
I realize the last comment from is from April but this issue is still marked Open. 

We are constantly having issues with comments not being realtime - near continuous refreshing or literally watching your email inbox to know when to refresh a page to see new comments. We are coming from pivotaltracker (which had its own massive shortcomings) and it excelled at in browser notification/realtime updating. Additionally, if you were on a page and received the notification in browser it wouldn't send out a (needless) email. We have definitely seen a huge uptick in emails since switching to tree.taiga.io

Love the product overall and have recommended it to many others, would just love to see an improvement in this area, thanks!
