### ISSUE TITLE
Sort cards alphabetically

### ISSUE THREAD

**Issue by KDWorsley** [taigaio/taiga-front#953]
Sorting cards alphabetically would be a great feature.

**Comment by superalex** [comment]
Hello @KDWorsley 

Most of teams keep their cards prioritized, highest priority on the top, could you please detail the scenario where this kind of sorting is useful?

Regards!,

**Comment by KDWorsley** [comment]
@superalex Yes, my team usually does the same, but we have some boards that track content-based tasks such as updates to pages, where it's helpful to be able to sort the card by the name of the card, which is the page name.

**Comment by superalex** [comment]
Ok @KDWorsley thank you for the explanation

**Comment by utjduo** [comment]
I'll push for this feature!
I'm using Taiga to keep track of all VFX that has to be done for feature films. We create every scene and take that has VFX in them as User Stories so we easy can assign them to a supervisor and also attach images, info and so on. The problem is that not all scenes are added chronological so scene 13 can be added after already adding 150 scenes and not having everything chronological is very messy.
Also after having 150 scenes in the kanvas makes it very hard to drag every US to the correct place, even more when you're adding 10 shots that needs to go to the top.

A simple way to fix this would be to simply sort by name!
