### ISSUE TITLE
Can see stories from multiple other taiga boards on my private backlog

### ISSUE THREAD

**Issue by minispeck** [taigaio/taiga-front#992]
Went into a US and then hit the back button.

suddenly had a bunch of stories on my backlog that aren't mine. i can't view details but this is reproducable. started happening minutes ago.
<img width="1130" alt="screen shot 2016-05-04 at 2 54 19 pm" src="https://cloud.githubusercontent.com/assets/12914451/15025672/67422df4-1208-11e6-84a7-01bb21e7d5c7.png">

**Comment by bameda** [comment]
Hi @minispeck 

We just solved this bug (https://github.com/taigaio/taiga-front/commit/f58dc55bbcf665e927b990878e523502cc666dd1). It happen because when the page is loading the pagination library sometime made request to the API without the project_id param that return stories of public projects, them it made a new call with your project_id and the two responses are mixed causing the backlog that you saw.

Thank you very much.
