### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Don42** [taigaio/taiga-front#994]
Many development tools support a dark theme. Switching from my IDE to taiga can be a bit blinding.
A dark theme would be helpful.

**Comment by Xaviju** [comment]
Anyone can develop a dark theme for Taiga and share it: https://taigaio.github.io/taiga-doc/dist/#themes Taiga is open to contributions.

**Comment by lonix1** [comment]
Dark theme would be great!

Are there any community themes anywhere? I've done some basic changes using stylish, but I want something more robust.

**Comment by madmath03** [comment]
It would be great to have a Dark Theme in Taiga.

I've also done some tweaks using Stylus, but I might try to develop a Taiga theme since I would use it as a show case for adding themes to [my company docker images for Taiga](https://github.com/Monogramm/docker-taiga).

I will share here as soon as I have something ready.

**Comment by burtsevyg** [comment]
> Anyone can develop a dark theme for Taiga and share it: https://taigaio.github.io/taiga-doc/dist/#themes Taiga is open to contributions.

This link does not work.

**Comment by Xaviju** [comment]
Hi! Thanks for reporting.
In Taiga6 we dropped preinstalled themes due to its low usage and high maintainability cost, but you can create your own or use any updated theme of the community.
 
We removed theme docs by mistake:
#https://github.com/taigaio/taiga-doc/pull/249

The URL will be soon available again.

**Comment by Xaviju** [comment]
URL is up again: https://taigaio.github.io/taiga-doc/dist/#themes
